export type MediaErrorCode = 'USER_NOT_VERIFIED' | 'MEDIA_TOO_LARGE' | 'MEDIA_UNSUPPORTED_TYPE' | 'MEDIA_INVALID_IMAGE' | 'MEDIA_NOT_FOUND' | 'MEDIA_NOT_OWNED' | 'MEDIA_NOT_READY' | 'MEDIA_STILL_ATTACHED' | 'MEDIA_NOT_VIEWABLE' | 'EVENT_NOT_FOUND' | 'EVENT_ORGANIZER_REQUIRED' | 'EVENT_MEDIA_NOT_EDITABLE' | 'EVENT_MEDIA_NOT_FOUND' | 'GALLERY_LIMIT_REACHED' | 'INVALID_ALT_TEXT' | 'MEDIA_ALREADY_ATTACHED';

export class MediaBusinessError extends Error {
  constructor(readonly code: MediaErrorCode) {
    super(code);
  }
}
