import { DataSource, In } from 'typeorm';
import { EventRecord } from '../events/events.persistence';
import { ParticipationOutcomeRecord } from '../participation/participation.persistence';
import { EventReviewRecord } from './feedback.persistence';
export class FeedbackBusinessError extends Error { constructor(readonly code: 'REVIEW_NOT_ELIGIBLE' | 'INVALID_REVIEW') { super(code); } }
export class FeedbackImplementation {
  constructor(private readonly dataSource: DataSource) {}
  async review(input: { eventId: string; actorUserId: string; subject: 'EVENT' | 'ORGANIZER'; rating: number; comment?: string }) {
    return this.dataSource.transaction(async (m) => { const event = await m.findOneBy(EventRecord, { id: input.eventId }); const attended = await m.findOneBy(ParticipationOutcomeRecord, { eventId: input.eventId, userId: input.actorUserId, outcome: 'ATTENDED' }); if (!event || !attended || event.organizerId === input.actorUserId) throw new FeedbackBusinessError('REVIEW_NOT_ELIGIBLE'); const previous = await m.getRepository(EventReviewRecord).findOne({ where: { eventId: input.eventId, authorUserId: input.actorUserId, subject: input.subject }, order: { createdAt: 'DESC', id: 'DESC' } }); return m.save(m.create(EventReviewRecord, { eventId: input.eventId, authorUserId: input.actorUserId, subject: input.subject, rating: input.rating, comment: input.comment?.trim() || null, supersedesReviewId: previous?.id ?? null })); });
  }
  async list(eventId: string, actorUserId?: string) { const rows = await this.dataSource.getRepository(EventReviewRecord).createQueryBuilder('review').where('review.event_id = :eventId', { eventId }).orderBy('review.created_at', 'DESC').addOrderBy('review.id', 'DESC').getMany(); const current = this.latest(rows, (row) => `${row.authorUserId}:${row.subject}`); return { summary: (['EVENT','ORGANIZER'] as const).map((subject) => this.summary(current.filter((review) => review.subject === subject), subject)), own: actorUserId ? current.filter((review) => review.authorUserId === actorUserId).map((review) => ({ subject: review.subject, rating: review.rating, comment: review.comment })) : [], recent: current.filter((review) => review.comment && review.subject === 'EVENT').slice(0, 4).map((review) => ({ rating: review.rating, comment: review.comment!, createdAt: review.createdAt })) }; }
  async organizerReviews(organizerUserId: string) { const rows = await this.dataSource.getRepository(EventReviewRecord).createQueryBuilder('review').innerJoin(EventRecord, 'event', 'event.id = review.event_id').where("event.organizer_id = :organizerUserId AND review.subject = 'ORGANIZER'", { organizerUserId }).orderBy('review.created_at', 'DESC').addOrderBy('review.id', 'DESC').getMany(); const current = this.latest(rows, (row) => `${row.authorUserId}:${row.eventId}`); const events = current.length ? await this.dataSource.getRepository(EventRecord).findBy({ id: In(current.map((review) => review.eventId)) }) : []; const eventTitles = new Map(events.map((event) => [event.id, event.title])); return { summary: this.summary(current, 'ORGANIZER'), recent: current.filter((review) => review.comment).slice(0, 6).map((review) => ({ rating: review.rating, comment: review.comment!, createdAt: review.createdAt, event: { id: review.eventId, title: eventTitles.get(review.eventId) ?? 'Etkinlik' } })) }; }
  private latest(rows: EventReviewRecord[], keyFor: (review: EventReviewRecord) => string) { const latest = new Map<string, EventReviewRecord>(); for (const row of rows) { const key = keyFor(row); if (!latest.has(key)) latest.set(key, row); } return [...latest.values()]; }
  private summary(reviews: EventReviewRecord[], subject: 'EVENT' | 'ORGANIZER') { return { subject, count: reviews.length, average: reviews.length ? Math.round(reviews.reduce((sum, review) => sum + review.rating, 0) / reviews.length * 10) / 10 : null, distribution: [5, 4, 3, 2, 1].map((rating) => ({ rating, count: reviews.filter((review) => review.rating === rating).length })) }; }
}
