export const CITY_OPTIONS = [
  ['Adana', 'Adana'], ['Adiyaman', 'Adıyaman'], ['Afyonkarahisar', 'Afyonkarahisar'], ['Agri', 'Ağrı'], ['Aksaray', 'Aksaray'], ['Amasya', 'Amasya'], ['Ankara', 'Ankara'], ['Antalya', 'Antalya'], ['Ardahan', 'Ardahan'], ['Artvin', 'Artvin'], ['Aydin', 'Aydın'], ['Balikesir', 'Balıkesir'], ['Bartin', 'Bartın'], ['Batman', 'Batman'], ['Bayburt', 'Bayburt'], ['Bilecik', 'Bilecik'], ['Bingol', 'Bingöl'], ['Bitlis', 'Bitlis'], ['Bolu', 'Bolu'], ['Burdur', 'Burdur'], ['Bursa', 'Bursa'], ['Canakkale', 'Çanakkale'], ['Cankiri', 'Çankırı'], ['Corum', 'Çorum'], ['Denizli', 'Denizli'], ['Diyarbakir', 'Diyarbakır'], ['Duzce', 'Düzce'], ['Edirne', 'Edirne'], ['Elazig', 'Elazığ'], ['Erzincan', 'Erzincan'], ['Erzurum', 'Erzurum'], ['Eskisehir', 'Eskişehir'], ['Gaziantep', 'Gaziantep'], ['Giresun', 'Giresun'], ['Gumushane', 'Gümüşhane'], ['Hakkari', 'Hakkari'], ['Hatay', 'Hatay'], ['Igdir', 'Iğdır'], ['Isparta', 'Isparta'], ['Istanbul', 'İstanbul'], ['Izmir', 'İzmir'], ['Kahramanmaras', 'Kahramanmaraş'], ['Karabuk', 'Karabük'], ['Karaman', 'Karaman'], ['Kars', 'Kars'], ['Kastamonu', 'Kastamonu'], ['Kayseri', 'Kayseri'], ['Kilis', 'Kilis'], ['Kirikkale', 'Kırıkkale'], ['Kirklareli', 'Kırklareli'], ['Kirsehir', 'Kırşehir'], ['Kocaeli', 'Kocaeli'], ['Konya', 'Konya'], ['Kutahya', 'Kütahya'], ['Malatya', 'Malatya'], ['Manisa', 'Manisa'], ['Mardin', 'Mardin'], ['Mersin', 'Mersin'], ['Mugla', 'Muğla'], ['Mus', 'Muş'], ['Nevsehir', 'Nevşehir'], ['Nigde', 'Niğde'], ['Ordu', 'Ordu'], ['Osmaniye', 'Osmaniye'], ['Rize', 'Rize'], ['Sakarya', 'Sakarya'], ['Samsun', 'Samsun'], ['Sanliurfa', 'Şanlıurfa'], ['Siirt', 'Siirt'], ['Sinop', 'Sinop'], ['Sirnak', 'Şırnak'], ['Sivas', 'Sivas'], ['Tekirdag', 'Tekirdağ'], ['Tokat', 'Tokat'], ['Trabzon', 'Trabzon'], ['Tunceli', 'Tunceli'], ['Usak', 'Uşak'], ['Van', 'Van'], ['Yalova', 'Yalova'], ['Yozgat', 'Yozgat'], ['Zonguldak', 'Zonguldak'],
] as const;

export type CityValue = (typeof CITY_OPTIONS)[number][0];

export function cityLabel(value: string) {
  return CITY_OPTIONS.find(([city]) => city === value)?.[1] ?? value;
}
